name: Version Bump

on:
  push:
    branches:
      - master

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Enable Corepack
        run: corepack enable

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Detect Branch
        id: detect-branch
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          if [ "$BRANCH_NAME" == "master" ]; then
            echo "VERSION_TYPE=minor" >> $GITHUB_ENV
            echo "COMMIT_MESSAGE=Minor versiyon arttırıldı" >> $GITHUB_ENV
          else
            echo "VERSION_TYPE=patch" >> $GITHUB_ENV
            echo "COMMIT_MESSAGE=Patch versiyon arttırıldı" >> $GITHUB_ENV
          fi

      - name: Bump Version
        run: node version-bump.js ${{ env.VERSION_TYPE }}

      - name: Get New Version
        id: get-version
        run: echo "NEW_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Update Footer Version
        run: |
          # Footer dosyasındaki versiyon satırını güncelle
          sed -i "s|<p>v[0-9]\+\.[0-9]\+\.[0-9]\+</p>|<p>v${{ env.NEW_VERSION }}</p>|g" src/modules/layout/templates/footer/index.tsx

      - name: Commit Changes
        run: |
          git add package.json src/modules/layout/templates/footer/index.tsx
          git commit -m "${{ env.COMMIT_MESSAGE }}: v${{ env.NEW_VERSION }}"
          git push 